image: node:18.19.1-alpine3.19

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm ci
    - ng build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  before_script:
    # Install openssh-client in alpine
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - scp -r dist/* $SSH_USER@$SSH_HOST:/path/to/your/webserver
  only:
    - master
