image: node:18.19.1-alpine3.19

stages:
  - build

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm ci
    - ng build
  artifacts:
    paths:
      - dist/
  only:
    - master
# deploy:
#   stage: deploy
#   before_script:
#     - 'apk add --update openssh'
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PASS" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#   script:
#     - echo "Deploying"
#     - scp mobile.tar.gz $SSH_USER@$SSH_HOST:/home/$SSH_USER/
#   only:
#     - master
