image: node:18.19.1-alpine3.19

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - PING -c 4 nithinglobal.in
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm ci
    - ng build
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - ping -c 4 $SSH_HOST
    - 'apk add --update openssh'
    - eval $(ssh-agent -s)
    - echo "$SSH_PASSWD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploying files to server..."
    - scp -r dist/* $SSH_USER@$SSH_HOST:/var/www/http
  only:
    - master
