image: node:18.19.1-alpine3.19

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm ci
    - ng build
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - echo "Before script 1"
    - apk add --no-cache openssh-client sshpass bind-tools busybox-extras iputils
    - echo "Before script 2"
    - mkdir -p ~/.ssh
    - echo "Before script 3"
    - chmod 700 ~/.ssh
    - echo "Before script 4"
    - ping -c 4 $SSH_HOST # Check if the host is reachable
    - echo "Before script 5"
    - nslookup $SSH_HOST # Check if the domain resolves correctly
    - echo "Before script 6"
    - telnet $SSH_HOST 22 # Test if the SSH port (22) is open and reachable
    - echo "Before script 7"
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - echo "Deploying files to server..."
    - scp -r dist/* $SSH_USER@$SSH_HOST:/var/www/http
  only:
    - master
