image: node:18.19.1-alpine3.19

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  when: manual
  script:
    - npm ci
    - ng build
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy:
  stage: deploy
  when: manual
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_HOST ssh-rsa $SSH_PUB" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploying files to server..."
    - scp -P 2222 -v -r dist/* $SSH_USER@$SSH_HOST:/var/www/html
  only:
    - master
